import type { TemplateFormat } from './types'

export const TEMPLATES: Record<string, TemplateFormat> = {
  DISC_SURFACE: {
    id: 'disc-surface',
    name: 'Disc Surface Sticker',
    displayName: 'DISC SURFACE STICKER',
    category: 'Disc Labels',  // Moved from 'Disc Surface' to 'Disc Labels'
    widthMM: 37,
    heightMM: 53,
    bleedMM: 3,
    hasBanner: true,
  },
  DISC_50x35: {
    id: 'disc-50x35',
    name: '50×35mm',
    displayName: 'DISC LABEL 50×35MM',
    category: 'Disc Labels',
    widthMM: 50,
    heightMM: 35,
    bleedMM: 3,
    hasBanner: false,
  },
  DISC_52x34: {
    id: 'disc-52x34',
    name: '52.5×34.5mm',
    displayName: 'DISC LABEL 52.5×34.5MM',
    category: 'Disc Labels',
    widthMM: 52.5,
    heightMM: 34.5,
    bleedMM: 3,
    hasBanner: false,
  },
  DISC_53x37: {
    id: 'disc-53x37',
    name: '53×37mm',
    displayName: 'DISC LABEL 53×37MM',
    category: 'Disc Labels',
    widthMM: 53,
    heightMM: 37,
    bleedMM: 3,
    hasBanner: false,
  },
  SPINE_60x3: {
    id: 'spine-60x3',
    name: '60×3mm',
    displayName: 'CARTRIDGE SPINE 60×3MM',
    category: 'Cartridge Spines',
    widthMM: 60,
    heightMM: 3,
    bleedMM: 3,
    hasBanner: false,
  },
  SPINE_59x3: {
    id: 'spine-59x3',
    name: '59×3.75mm',
    displayName: 'CARTRIDGE SPINE 59×3.75MM',
    category: 'Cartridge Spines',
    widthMM: 59,
    heightMM: 3.75,
    bleedMM: 3,
    hasBanner: false,
  },
  CASE_70x50: {
    id: 'case-70x50',
    name: '70×50mm',
    displayName: 'SLIDE CASE 70×50MM',
    category: 'Slide Cases',
    widthMM: 70,
    heightMM: 50,
    bleedMM: 3,
    hasBanner: false,
  },
  CASE_71x52: {
    id: 'case-71x52',
    name: '71×52mm',
    displayName: 'SLIDE CASE 71×52MM',
    category: 'Slide Cases',
    widthMM: 71,
    heightMM: 52,
    bleedMM: 3,
    hasBanner: false,
  },
  INSERT_104x101: {
    id: 'insert-104x101',
    name: '104×101.5mm',
    displayName: 'CASSETTE INSERT 104×101.5MM',
    category: 'Cassette Inserts',
    widthMM: 104,
    heightMM: 101.5,
    bleedMM: 3,
    hasBanner: false,
  },
  INSERT_65x101: {
    id: 'insert-65x101',
    name: '65×101.5mm',
    displayName: 'CASSETTE INSERT 65×101.5MM',
    category: 'Cassette Inserts',
    widthMM: 65,
    heightMM: 101.5,
    bleedMM: 3,
    hasBanner: false,
  },
  INSERT_12x101: {
    id: 'insert-12x101',
    name: '12.5×101.5mm',
    displayName: 'CASSETTE INSERT 12.5×101.5MM',
    category: 'Cassette Inserts',
    widthMM: 12.5,
    heightMM: 101.5,
    bleedMM: 3,
    hasBanner: false,
  },
  INSERT_26x101: {
    id: 'insert-26x101',
    name: '26.5×101.5mm',
    displayName: 'CASSETTE INSERT 26.5×101.5MM',
    category: 'Cassette Inserts',
    widthMM: 26.5,
    heightMM: 101.5,
    bleedMM: 3,
    hasBanner: false,
  },
  ALBUM_FRONT: {
    id: 'album-front',
    name: '106×101.5mm (Front)',
    displayName: 'ALBUM INSERT 106×101.5MM (FRONT)',
    category: 'Album Inserts',
    widthMM: 106,
    heightMM: 101.5,
    bleedMM: 3,
    hasBanner: false,
  },
  ALBUM_REAR: {
    id: 'album-rear',
    name: '106×101.5mm (Rear)',
    displayName: 'ALBUM INSERT 106×101.5MM (REAR)',
    category: 'Album Inserts',
    widthMM: 106,
    heightMM: 101.5,
    bleedMM: 3,
    hasBanner: false,
  },
  ALBUM_ROLLFOLD: {
    id: 'album-rollfold',
    name: '428×105mm (Rollfold)',
    displayName: 'ALBUM INSERT 428×105MM (ROLLFOLD)',
    category: 'Album Inserts',
    widthMM: 428,
    heightMM: 105,
    bleedMM: 3,
    hasBanner: false,
  },
}

export const DEFAULT_TEMPLATE = TEMPLATES.DISC_SURFACE

export const TEMPLATE_CATEGORIES = [
  'Disc Labels',  // Now includes Disc Surface Sticker
  'Cartridge Spines',
  'Slide Cases',
  'Cassette Inserts',
  'Album Inserts',
]

// Version information
export const VERSION = '0.3.7g';

export const VERSION_INFO = {
  version: '0.3.7g',
  releaseDate: '2026-02-07',
  releaseName: '5 Artwork Sources',
  features: '5 artwork sources active',
};

